version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: organicfruits-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - og-network

  backend:
    build:
      context: ./backend-java
    container_name: organicfruits-java-api
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/organicfruits
      - APP_JWT_SECRET=your_very_long_random_secret_key_for_production
    depends_on:
      - mongodb
    networks:
      - og-network

  frontend:
    build:
      context: ./frontend
    container_name: organicfruits-web
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - og-network

networks:
  og-network:
    driver: bridge

volumes:
  mongo_data:
