services:
  - name: backend
    type: web
    env: docker
    build:
      context: ./backend-java
    ports:
      - "5000:5000"
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster0.mongodb.net/organicfruits?retryWrites=true&w=majority
      - key: APP_JWT_SECRET
        value: your_secret_key

  - name: frontend
    type: web
    env: docker
    build:
      context: ./frontend
    ports:
      - "8080:80"