version: '3.8'


services:
  backend:
    build:
      context: ./backend-java
    container_name: organicfruits-java-api
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=YOUR_ATLAS_URI_HERE
      - APP_JWT_SECRET=${JWT_SECRET:-your_very_long_random_secret_key_for_production_change_me}
  frontend:
    build:
      context: ./frontend
    container_name: organicfruits-web
    ports:
      - "8080:80"
    depends_on:
      - backend
