services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerContext: ./backend-java
    dockerfilePath: ./backend-java/Dockerfile
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://sumit:C6ug9QY0HAHvrGTc@cluster0.wlhenqg.mongodb.net/?appName=Cluster0
      - key: APP_JWT_SECRET
        value: your_secret_key

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile