services:
  - type: web
    name: backend
    env: docker
    plan: free
    dockerContext: ./backend-java
    dockerfilePath: ./backend-java/Dockerfile
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster0.mongodb.net/organicfruits
      - key: APP_JWT_SECRET
        value: your_secret_key

  - type: web
    name: frontend
    env: docker
    plan: free
    dockerContext: ./frontend
    dockerfilePath: ./backend-java/Dockerfile