server.port=5000
spring.data.mongodb.uri=mongodb+srv://sumit:C6ug9QY0HAHvrGTc@cluster0.wlhenqg.mongodb.net/organicfruits?retryWrites=true&w=majority&appName=Cluster0

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.organicfruits.api=DEBUG

# JWT
app.jwt.secret=dev_secret_change_me_dev_secret_change_me_must_be_long_enough
app.jwt.expiration=604800000
